version: '3.8'

services:
  aaaver-app:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "6110:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}